### ISSUE TITLE
Problem with clsql_mysql.dll

### ISSUE THREAD

**Issue by ghost** [UnwashedMeme/clsql#9]
Windows 10 64-bit 
SBCL 1.3.12
MySQL 5.7

I'm trying to connect to the database system of the through (connect '( "localhost" "name" "user" "pass"): database-type: mysql) and get:  Couldn't load foreign libraries "clsql_mysql64", "clsql_mysql". (searched *FOREIGN-LIBRARY-SEARCH-PATHS*: (#P"Z:/Lisp/.quicklisp/dists/quicklisp/software/clsql-20160208-git/db-mysql/"))
 0: [TRY-RECOMPILING] Recompile mysql-loader and try loading it again
 1: [RETRY] Retry loading FASL for #<CL-SOURCE-FILE "clsql-mysql" "db-mysql" "mysql-loader">.
 2: [ACCEPT] Continue, treating loading FASL for #<CL-SOURCE-FILE "clsql-mysql" "db-mysql" "mysql-loader"> as having been successful.
 3: [RETRY] Retry ASDF operation.
 4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 5: [ABORT] Abort compilation.

Here is what I found on google: 

> Hi,
> 
> I'm quite new to Lisp and I ran into the same problem today.
> 
> In my case it was because of the file clsql_mysql.dll didn't work
> correct (that is when using it under windows).
> If this was due to some broken dependency in the dll or not I'm not
> sure of but I rebuilt the dll and the problem was fixed.
> I'm not sure if this will help you but hopefully it will.

http://comp.lang.lisp.narkive.com/yEv8KJNw/lispworks-and-clsql

The file clsql_mysql.dll is not there, but it is very necessary to me.

**Comment by bobbysmith007** [comment]
Are you building under cygwin? (I am guessing not)

It doesn't look like there is any appropriate make configuration for windows.  Maybe check the db-mysql Makefile and see if you can get it configured correctly for windows.  It will need the compile flags and load flags set with the correct locations.

**Comment by keks777** [comment]
Ok, I created a new clsql_mysql.dll and when I try to connect now the error: The function MYSQL:MYSQL-GET-CLIENT-INFO is undefined.

**Comment by bobbysmith007** [comment]
Sorry to have not responded, I'm sure I was quite busy and didnt have an answer.  I dont use windows or lisp works, and try not to use much mysql, so its really not my area of expertise.  There is some folks talking about it on the mailing list now and if something comes up I will post it here and maybe in the manual

**Comment by bobbysmith007** [comment]
Just wanted to point out that this is probably resolved now from #11 please reopen if needed and thanks to those involved in making this happen

**Comment by tdrhq** [comment]
(EDIT: oops, meant to comment on the PR: https://github.com/UnwashedMeme/clsql/pull/11#issuecomment-692214887)
